codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "85...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 85%
        threshold: 10%
        if_not_found: success
        if_ci_failed: error

  ignore:
    - "tests/"
    - "examples/"
    - "docs/"
    - "setup.py"
    - "openembeddings/__main__.py"

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

github_checks:
  annotations: true 